sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
script:
  - sk-bundle
  - if [ "<%= "${TRAVIS_SECURE_ENV_VARS}" %>" = "true" ]; then
    npm test -- --testingbot;
    else
    npm test -- --browsers Firefox;
    fi
after_success:
  - sk-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
