sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: stable
before_script:
  - npm prune
install:
  - npm install -g yarn
  - yarn install
after_success:
  - ./bin/sk-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
